project:
  type: website

website:
  title: "Diane & Teo Science"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  back-to-top-navigation: true
  favicon: files/loupe_rounded.png
  page-footer:
    center: |
      *Site réalisé avec [Quarto](https://quarto.org/)*
    border: false
  navbar:
    title: false
    logo: files/logo_loupe.png
    left:
      - icon: bi-house
        text: Accueil
        href: index.qmd
      - icon: bi-bar-chart
        text: Analyses
        href: analyses/index.qmd
      - icon: bi-book
        text: Formations
        href: formations/index.qmd
      - icon: bi-list-ul
        text: Ressources
        href: ressources/index.qmd
      - icon: bi-basket3
        text: Autres
    right:
      - icon: github
        href: https://github.com/diane-teo
      - icon: linkedin
        href: https://www.linkedin.com/in/teodoro-mounier-tebas-a423341a3
      
lang: fr
format:
  html:
    theme: styles.scss
    grid:
      body-width: 1000px
