project:
  type: website

website:
  title: "Diane & Teo Science"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Site réalisé avec [Quarto](https://quarto.org/)"
  navbar:
    logo: Diane & Teo.png
    left:
      - text: Home
        href: index.qmd
      - text: test
        href: test.qmd
      
format:
  html:
    theme: [Cosmo, styles.scss]
