project:
  type: website

website:
  title: "Diane & Teo Science"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  back-to-top-navigation: true
  favicon: files/logo.png
  page-footer:
    center: |
      *Site réalisé avec [Quarto](https://quarto.org/)*
    border: false
  navbar:
    title: false
    logo: files/logo.png
    left:
      - icon: bi-house
        text: Accueil
        href: index.qmd
      - icon: bi-clipboard-data
        text: Analyses
        href: test.qmd
      - icon: bi-easel
        text: Cours
    right:
      - icon: github
        href: https://github.com/teodoromouniertebas
      - icon: linkedin
        href: https://www.linkedin.com/in/teodoro-mounier-tebas-a423341a3
      
lang: fr
format:
  html:
    theme: [cosmo, styles.scss]
